### ISSUE TITLE
Cant get Set-NsxEdgeInterface to work

### ISSUE THREAD

**Issue by marcfong** [vmware/powernsx#21]
I am trying to use PowerNSX to programatically enable a NSX Edge interface as apart of a SRM Recovery Plan.

I tried doing some of the examples in the code but could not get the Set-NSXEdgeInterface command to work for me.

`PowerCLI C:\> $interface = Get-NsxEdge "Provider-ESG-01" | Get-NsxEdgeInterface -Index 0
PowerCLI C:\> $interface

label               : vNic_0
name                : user-net
addressGroups       : addressGroups
mtu                 : 1500
type                : uplink
isConnected         : true
index               : 0
portgroupId         : dvportgroup-120
portgroupName       : DPG-User-NET-A-172.17.X.X
enableProxyArp      : false
enableSendRedirects : false
edgeId              : edge-1

PowerCLI C:\> $interface |Set-NsxEdgeInterface -Name "vNic4" -Type internal
Set-NsxEdgeInterface : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:13
+ $interface |Set-NsxEdgeInterface -Name "vNic4" -Type internal
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-NsxEdgeInterface], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Set-NsxEdgeInterface`

**Comment by nmbradford** [comment]
Unfortunately, Set-NsxEdgeInterface will overwrite the config of the interface rather than incrementally change it as you want.  What is missing from PowerNSX is an Update-NsxEdgeInterface cmdlet.  I'm sure this wont be the last time you come across this limitation in various places as the update cmdlets are typically harder to write.  Feel free to raise it as a separate issue if you want to get support for it being added.

You also hit a bug (the cmdlet should force you to specify the required params rather than barf, but its been the victim of a parameterset rename in the past and the default parameterset specified doesnt exist - dont worry if this doesnt mean anything to you, but Ill raise a separate issue to track and resolve this as its an easy fix.)

There are two ways of dealing with this for now.

1) Specify all required parameters (Name, Type, PrimaryAddress, netmask, connected-to, connected) when calling set-nsxedgeinterface.

2) Use the ability of the set-nsxedge cmdlet to manipulate the XML directly as follows (This requires you manipulate the XML defining the edge directly and does not do any input validation - make sure you change the right thing!).  Also note: This will trigger a redeploy of the edge.

```
#To disable vnic 0
$edge = get-nsxedge
$vnic = $edge.vnics.vnic | ? { $_.index -eq 0 }
$vnic.isConnected = "false"
$edge | set-nsxedge
```
```
#To enable vnic 0
$edge = get-nsxedge
$vnic = $edge.vnics.vnic | ? { $_.index -eq 0 }
$vnic.isConnected = "true"
$edge | set-nsxedge
```

**Comment by nmbradford** [comment]
Following up - to avoid a redeploy of the edge, even though PowerNSX doesnt support just toggling the interface connected state with native cmdlets, you can still use the Invoke-NsxRestMethod PowerNSX command to easily modify the XML representing the interface directly and post it to the API youself as follows:

Disconnect an Edge vnic:
```
#Get the Edge and interface you want to modify
$edge = get-nsxedge edge01
$uplink = $edge | Get-NsxEdgeInterface -Index 0

#Get the edgeid child elem that powernsx adds to aid pipeline operations...
$edgeid = $uplink.SelectSingleNode("child::edgeId")

#...and remove it from the xml we send to the api, otherwise it will error.
[void]$uplink.RemoveChild($edgeid)

#Toggle connected (or any other elem you want...)
$uplink.isConnected = "false"

#Call the API.  Using Invoke-NsxRestMethod means we dont need server name, protocol, port, content-type header or authentication header. 
#This all comes from the PowerNSX $defaultnsxconnection object created when we run Connect-NsxServer
Invoke-NsxRestMethod -method put -URI "/api/4.0/edges/$($edge.id)/vnics/$($uplink.index)" -body $uplink.OuterXml
```

To reconnect the vnic:
```
$edge = get-nsxedge edge01
$uplink = $edge | Get-NsxEdgeInterface -Index 0
$edgeid = $uplink.SelectSingleNode("child::edgeId")
[void]$uplink.RemoveChild($edgeid)
$uplink.isConnected = "true"
Invoke-NsxRestMethod -method put -URI "/api/4.0/edges/$($edge.id)/vnics/$($uplink.index)" -body $uplink.OuterXml
```
