### ISSUE TITLE
Need member details for nsxservice and nsxservicegroup

### ISSUE THREAD

**Issue by haribcs** [vmware/powernsx#404]
Hi,

Im trying to retrieve 2 outputs as i see in GUI.
1. get-nsxservice with name,protocol,destination and source ports. however i get only name
2. get-nsxservicegroup with Name,details, Only getting Name

is there anyway to achieve this?

Thanks

**Comment by dcoghlan** [comment]
The first can be achieved as follows
```
get-nsxservice  | select name,isuniversal,@{Name='Protocol'; Expression={$_.element.applicationprotocol}},@{Name='SrcPort'; Expression={$_.element.sourceport}},@{Name='DstPort'; Expression={$_.element.value}},description | ft -wrap -autosize
```
Just make sure your window/console size is wide enough to fit all the output in otherwise some of it won't be displayed due to the large name and description fields.

The second is a bit trickier to display in a console as Powershell will truncate the output of an array and only display the number of entries defined in $FormatEnumerationLimit by default.
```
get-nsxservicegroup | select name, member | ft -AutoSize -wrap
```

There will be some service groups that have more than 4 members, and if you want to display them all on the console, then set 
```
$FormatEnumerationLimit = -1
```

Alternatively, take a look at the DFW2Excel tool which will grab all the details for you and place them in a spreadsheet for easy viewing.
https://github.com/tonysangha/PowerNSX-DFW2Excel

**Comment by nmbradford** [comment]
Thanks @dcoghlan.  Only thing to add to that is for the first example, you dont have to display as a table (replace | ```ft -autosize -wrap``` with ```| fl```) - then you don't have to worry about not fitting everything in the window width...
