### ISSUE TITLE
Need Loadbalancer outputs should be in one line

### ISSUE THREAD

**Issue by vTechworld** [vmware/powernsx#515]
Hi Team, 
Can it be possible out put these commands in one line and get one single output.
Get-NsxLoadBalancer
Get-NsxLoadBalancerApplicationProfile
Get-NsxLoadBalancerApplicationRule
Get-NsxLoadBalancerMonitor
Get-NsxLoadBalancerPool
Get-NsxLoadBalancerPoolMember
Get-NsxLoadBalancerStats
Get-NsxLoadBalancerVip

**Comment by nmbradford** [comment]
Hi @vTechworld - this is definitely an exercise for the user!  Manipulating output to a desired state is something that PoSH is very good at, but you will have to deal with the issues caused by 1:many relationships between some of the entities you list (pools to members as example) and what details make sense to you to include.  This is not something that should be dealt with by PowerNSX internally (in the same way that PowerCLI requires you to get harddisk, network adapter, resource configuration etc details separately from getting a VM).

The way I would tackle this is to determine what you want in your output, then for a given LB iteration, construct a PSCustomObject and populate it with the properties that you want.  This is a pretty typical day in the life of a PoSH'er! :)

Hope this helps.
