### ISSUE TITLE
API Call error in the PowerNSX module

### ISSUE THREAD

**Issue by agiorgi** [vmware/powernsx#526]
Hi all:

If you pay attention to the screen capture, sometime the cmdlet in the powerNSX module who make the api call to get the IPSet objects, get a 400 error and abort my script.
Are there any workarround to resolve this problem?
May I user tha api call directly from my script instead use the cmdlet?
What do you recommend? 
Thanks in advance.

<img width="1440" alt="screen shot 2018-06-25 at 11 41 21" src="https://user-images.githubusercontent.com/11071836/42035729-ef4014e6-7ae3-11e8-9dfc-fb8919596fe4.png">

**Comment by dcoghlan** [comment]
Hi @agiorgi 

The error being displayed is due to a limitation in NSX-v.

When working with IPSets, you generally cannot have an empty IPSet. The exception to this is that the API (and only the API) will allow you to create an empty IPSet.... go figure.

If you try and remove the last IP address in an IPSet, both the UI and API will throw an error. The API in particular will actually throw a 400 error and give you a very non-descript message, so we took the decision to throw with a more descriptive message before even sending the request as we know whats going to happen.

If you actually want to remove the last IP address in an IPSet, what we advise people to do is to first add a "placeholder" IP address to the IPSet in question, and make it an address that you'll never remove, but also one that is not routable or accessible on your network. That way there can always be "something" in the IP Set, once you add/remove all your other "real" addresses.

Unfortunately this is the best workaround for this particular situation.

Hope it helps.

Dale

**Comment by agiorgi** [comment]
Thanks Dale.

I will try to modify my script assuring there are at least one IP address in the IPSet.

Regards


________________________________
De: Dale Coghlan <notifications@github.com>
Enviado: viernes, 29 de junio de 2018 1:34
Para: vmware/powernsx
Cc: agiorgi; Mention
Asunto: Re: [vmware/powernsx] API Call error in the PowerNSX module (#526)


Hi @agiorgi<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fagiorgi&data=02%7C01%7C%7C92c57605f9364371329208d5dd4fbe67%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636658256914078988&sdata=F871lYDD0cGSaLsXfBBgS5%2By9DPpa86MsEsjnopZGu8%3D&reserved=0>

The error being displayed is due to a limitation in NSX-v.

When working with IPSets, you generally cannot have an empty IPSet. The exception to this is that the API (and only the API) will allow you to create an empty IPSet.... go figure.

If you try and remove the last IP address in an IPSet, both the UI and API will throw an error. The API in particular will actually throw a 400 error and give you a very non-descript message, so we took the decision to throw with a more descriptive message before even sending the request as we know whats going to happen.

If you actually want to remove the last IP address in an IPSet, what we advise people to do is to first add a "placeholder" IP address to the IPSet in question, and make it an address that you'll never remove, but also one that is not routable or accessible on your network. That way there can always be "something" in the IP Set, once you add/remove all your other "real" addresses.

Unfortunately this is the best workaround for this particular situation.

Hope it helps.

Dale
