### ISSUE TITLE
How to Add More Services on an Existing Service Group ?

### ISSUE THREAD

**Issue by RS30** [vmware/powernsx#533]
Hi, 

I am working on an issue where we have to add more services to an existing Service Group. is there a way to do it ?

so far I have written the scripts to build services and copy an existing services under the Services groups. I am seeking help to add more services to an existing services Group.

**Comment by alagoutte** [comment]
Hi,

You can use Add-NsxServiceGroupMember from Example... (need to be enhance...)

Get-NsxServiceGroup Heartbeat | Add-NsxServiceGroupMember -Member $Service1

**Comment by nmbradford** [comment]
@alagoutte is correct - you should pass the service _object_ in the call to add-nsxservicegroupmember (Not the name of the member).  

```
$service = get-nsxservice test-1234
get-nsxservicegroup test-group-2 | add-nsxservicegroupmember -member $service.
```

Your first attempt is not working because you chose a poor variable name 'TEST-1234'.  The use of the '-' character in the variable name causes PowerShell to see it as a word break when doing string interpolation (see how PowerShell says 'Cannot convert the "-1234" string value to xml'???  Note that its only a PART of your variable name?).  

From https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_variables?view=powershell-6 : 'Variable names are not case-sensitive. Variable names can include spaces and special characters, but these are difficult to use and should be avoided.'

**Comment by mir1218** [comment]
thanks :100:

**Comment by mir1218** [comment]
How can I add multiple variables 

$service = get-nsxservice test-1234 , test-3 , test4
     or
$service = get-nsxservice test-1234  test-3  test4

**Comment by nmbradford** [comment]
```
$svc1 = get-nsxservice test-1234
$svc2 = get-nsxservice test-3
$svc3 = get-nsxservice test4
get-nsxservicegroup test-group-2 | Add-NsxServiceGroupMember -Member $svc1, $svc2, $svc3
```
or (using a regex to return a collection of services)

```
$services = get-nsxservice | ? { $_.name -match 'test' } 
get-nsxservicegroup test-group-2 | Add-NsxServiceGroupMember -Member $services
```

This is not PowerNSX specific stuff.  Sounds like some basic PowerShell learning might be a good place for you to start?
