### ISSUE TITLE
[Win] Update-PowerNsx with Branch specified throws error

### ISSUE THREAD

**Issue by dcoghlan** [vmware/powernsx#86]
When specifying a branch in update-powernsx, the following error is displayed.

PowerCLI C:\Windows\system32> Update-PowerNsx -Branch master
Update-PowerNsx : Cannot validate argument on parameter 'Branch'. The term 'Validate-UpdateBranch' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:25
+ Update-PowerNsx -Branch master
+                         ~~~~~~
    + CategoryInfo          : InvalidData: (:) [Update-PowerNsx], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Update-PowerNsx

PowerCLI C:\Windows\system32> $psversiontable

Name                           Value
----                           -----
PSVersion                      3.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.18444
BuildVersion                   6.2.9200.16481
PSCompatibleVersions           {1.0, 2.0, 3.0}
PSRemotingProtocolVersion      2.2

**Comment by nmbradford** [comment]
i cant repro this, but it implies that the function update-powernsx was loaded into the global scope rather than being exported from the module.  Ive seen this happen due to concurrent runs of update-powernsx without restarting the session, but thought Id fixed it.

Either way, ive just done a number of updates to update-powernsx (and the installer) to support core, and this issue should be resolved because I no longer reload the module (rather, user is prompted to restart the powershell session.).  This is for a number of reasons, but at a high level the module autoload/unload and dependency stack with powercli was causing issues including ones like this.

update-powernsx -branch master and then restart your powershell session and issues should be gone.  See PR #89 for details.
